# Generated by Django 5.0.1 on 2024-01-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='whatsapp',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
