# Generated by Django 5.0.1 on 2024-01-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service\\static\\service\\images'),
        ),
    ]
