# Generated by Django 5.0.1 on 2024-01-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='partner_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
