# Generated by Django 5.0.1 on 2024-01-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.ImageField(null=True, upload_to='images/logo'),
        ),
    ]
