# Generated by Django 5.0.1 on 2024-01-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_about_logo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='logo2',
            field=models.ImageField(null=True, upload_to='images/logo'),
        ),
    ]
